# Generated by Django 6.0 on 2026-02-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_driver_team_result_teamstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='round',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('season', 'round')},
        ),
    ]
