# Generated by Django 6.0 on 2026-02-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_session_session_type_result_teamstanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(max_length=100),
        ),
    ]
